### PR TITLE
Replace PhantomJS & Migrate eslint-config-edx

### PR DESCRIPTION
**Pull request by BilalQamar95**
**Description:**

- Replaced PhantomJS with Headless Chromium
- Replaced the deprecated eslint-config-edx with the newer @edx/eslint-config package

**Git Issue:**

- [79](https://github.com/edx/upgrades/issues/79)
- [81](https://github.com/edx/upgrades/issues/81)

**Pre-Merge Checklist:**

- [x] Updated the version number in `edx_proctoring/__init__.py` and `package.json` if these changes are to be released.
- [x] Described your changes in `CHANGELOG.rst`
- [x] Confirmed Github reports all automated tests/checks are passing.
- [x] Approved by at least one additional reviewer.

**Post-Merge:**

- [ ] Create a tag matching the new version number.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @BilalQamar95! I've created [OSPR-6752](https://openedx.atlassian.net/browse/OSPR-6752) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@BilalQamar95 Thank you for the contribution! Once you have filed the forms and they have been processed, we will be able to review this and all your future code contributions.

**Comment by natabene** [comment]
@BilalQamar95 All checks have passed, so I will line this up for our review.

**Review by davidjoy — APPROVED** [review]
This seems like a fine change - more complex than some of the other changes Fed-BOM has been making, so I think the owning team should review the phantom changes carefully.  I did a cursory review.

**Comment by Zacharis278** [comment]
This looks good to me. Did a quick smoke test on the instructor views that would be impacted, everything learner facing will only be accessed through the learning MFE after Nutmeg.

@BilalQamar95 can you add a changelog entry and bump the version numbers as listed in the PR template?

**Review by Zacharis278 — APPROVED** [review]

**Comment by BilalQamar95** [comment]
> This looks good to me. Did a quick smoke test on the instructor views that would be impacted, everything learner facing will only be accessed through the learning MFE after Nutmeg.
> 
> @BilalQamar95 can you add a changelog entry and bump the version numbers as listed in the PR template?

Updated version to 4.11.0 & added summary of changes to changelog

**Pull request merged**
