### PR TITLE
feat: remove IDV references from proctoring

### PR DESCRIPTION
**Pull request by alangsto**
**Description:**

Remove IDV as a prerequisite to proctoring. 

**JIRA:**

[MST-1378](https://openedx.atlassian.net/browse/MST-1378)

**Pre-Merge Checklist:**

- [x] Updated the version number in `edx_proctoring/__init__.py` and `package.json` if these changes are to be released.
- [ ] Described your changes in `CHANGELOG.rst`
- [ ] Confirmed Github reports all automated tests/checks are passing.
- [ ] Approved by at least one additional reviewer.

**Post-Merge:**

- [ ] Create a tag matching the new version number.

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍

**Comment by Zacharis278** [comment]
for the merge commit I think you will need to tag this as "feat", I think chore won't bump the version.

**Review by Zacharis278 — APPROVED** [review]

**Comment by alangsto** [comment]
> for the merge commit I think you will need to tag this as "feat", I think chore won't bump the version.

If only there were a `remove` conventional commit... I'll update the commit messages for these PRs to `feat`

**Comment by Zacharis278** [comment]
wait, this is the wrong PR. I meant to comment on https://github.com/edx/frontend-lib-special-exams/pull/64

**Pull request merged**
